export const DUMMY_CONVERSATIONS = [
  {
    id: 1,
    serial_id: "CONVO-001",
    email_id: "johncena@test.com",
    status: "Resolved",
    last_messaged_at: "15 Jan 2026, 12:30",
  },
  {
    id: 2,
    serial_id: "CONVO-002",
    email_id: "greatkhali@test.com",
    status: "Partially resolved",
    last_messaged_at: "22 Mar 2025, 22:45",
  },
  {
    id: 3,
    serial_id: "CONVO-003",
    email_id: "undertaker@test.com",
    status: "Unresolved",
    last_messaged_at: "10 Feb 2026, 09:10",
  },
  {
    id: 4,
    serial_id: "CONVO-004",
    email_id: "romanreigns@test.com",
    status: "Resolved",
    last_messaged_at: "28 Jan 2026, 18:20",
  },
  {
    id: 5,
    serial_id: "CONVO-005",
    email_id: "sethrollins@test.com",
    status: "Partially resolved",
    last_messaged_at: "02 Apr 2025, 14:55",
  },
  {
    id: 6,
    serial_id: "CONVO-006",
    email_id: "brocklesnar@test.com",
    status: "Unresolved",
    last_messaged_at: "19 Dec 2025, 11:05",
  },
  {
    id: 7,
    serial_id: "CONVO-007",
    email_id: "ajstyles@test.com",
    status: "Resolved",
    last_messaged_at: "05 Jan 2026, 16:40",
  },
  {
    id: 8,
    serial_id: "CONVO-008",
    email_id: "randyorton@test.com",
    status: "Unresolved",
    last_messaged_at: "11 Nov 2025, 20:15",
  },
  {
    id: 9,
    serial_id: "CONVO-009",
    email_id: "edge@test.com",
    status: "Partially resolved",
    last_messaged_at: "07 Feb 2026, 10:00",
  },
  {
    id: 10,
    serial_id: "CONVO-010",
    email_id: "batista@test.com",
    status: "Resolved",
    last_messaged_at: "01 Mar 2026, 08:35",
  },
];
